[workspace]
members = ["core", "desktop", "web"]

[patch.crates-io]
dioxus = { path = "../../dioxus/packages/dioxus" }
dioxus-desktop = { path = "../../dioxus/packages/desktop" }
dioxus-web = { path = "../../dioxus/packages/web" }
